### ISSUE TITLE
TypeScript compilation fails with "Cannot find module 'yahoo-finance2'" after updating to v3.6.5

### ISSUE THREAD

**Issue by unav4ila8le** [gadicc/yahoo-finance2#948]
# Bug Report

## Describe the bug
After updating yahoo-finance2 to version 3.6.5, TypeScript compilation fails with the error "Cannot find module 'yahoo-finance2' or its corresponding type declarations." This affects all imports of the package across the codebase.

## Minimal Reproduction
```
import YahooFinance from "yahoo-finance2";
// or
import yahooFinance from "yahoo-finance2";

const yahoo = new YahooFinance();
// or
await yahooFinance.quote('AAPL');
```

## Environment
Browser or Node: node
Node version (if applicable): 22+
Npm version: 10+
Browser version (if applicable): N/A
Library version: 3.6.5

## Additional Context
The error occurs in all the files that import yahoo-finance2
The package was working correctly before the update

**Comment by gadicc** [comment]
Thanks for the report, @unav4ila8le!  There will be a fix out momentarily.
